language: rust

services:
  - docker

addons:
  apt:
    packages: [valgrind]

jobs:
  include:
  - os: linux
    arch: amd64
    rust: stable
  - os: linux
    arch: amd64
    rust: nightly-2019-10-17
    env: RDKAFKA_RUN_TESTS=1
  - os: linux
    arch: arm64
    rust: stable
  - os: osx
    rust: stable
  - os: windows
    arch: amd64
    rust: stable
    env: FEATURES=cmake_build,libz-static

script:
  - |
    if [[ "$RDKAFKA_RUN_TESTS" ]]; then
      ./test_suite.sh
    else
      cargo build --all-targets --verbose --features "$FEATURES"
    fi

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2826b9d85e25802b3907  # gitter
    on_success: change
    on_failure: always
    on_start: never
